format = """
$directory\
$character\
"""

palette = "kanagawa_dragon"

[palettes.kanagawa_dragon]
blue = "#8ba4b0"
violet = "#8992a7"
green = "#8a9a7b"
red = "#c4746e"
yellow = "#c4b28a"
cyan = "#8ea4a2"
gray = "#737c73"
dark = "#393836"

[directory]
style = "bold blue"
truncation_length = 1
format = "([$path]($style) )([$read_only]($read_only_style) )"

[directory.substitutions]
"~/" = ""
"~" = ""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
