#!/usr/bin/env bash

export CONFIG_DIR="$HOME/.config/sketchybar"
source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

PLUGINS="$CONFIG_DIR/plugins"
FONT="JetBrainsMono NF"

sketchybar --bar \
  height=32 \
  position=top \
  padding_left=8 \
  padding_right=8 \
  color="$BAR" \
  border_width=0 \
  shadow=off \
  topmost=on

sketchybar --default \
  updates=when_shown \
  icon.font="$FONT:Bold:14.0" \
  icon.color="$FG" \
  icon.padding_left=6 \
  icon.padding_right=4 \
  label.font="$FONT:Medium:13.0" \
  label.color="$FG" \
  label.padding_left=0 \
  label.padding_right=6 \
  background.corner_radius=5 \
  background.height=22

sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
  sketchybar \
    --add item "space.$sid" left \
    --subscribe "space.$sid" aerospace_workspace_change \
    --set "space.$sid" \
    icon="$sid" \
    icon.padding_left=9 \
    icon.padding_right=9 \
    label.drawing=off \
    background.color="$SURFACE_HI" \
    background.drawing=off \
    click_script="aerospace workspace $sid" \
    script="$PLUGINS/aerospace.sh $sid"
done

sketchybar \
  --add item front_app left \
  --subscribe front_app front_app_switched \
  --set front_app \
  icon.drawing=off \
  label.color="$BLUE" \
  label.font="$FONT:Bold:13.0" \
  label.padding_left=9 \
  script="$PLUGINS/front_app.sh"

sketchybar \
  --add item clock right \
  --set clock \
  update_freq=10 \
  icon="$ICON_CLOCK" \
  icon.color="$VIOLET" \
  script="$PLUGINS/clock.sh"

sketchybar \
  --add item battery right \
  --subscribe battery power_source_change system_woke \
  --set battery \
  update_freq=120 \
  script="$PLUGINS/battery.sh"

sketchybar \
  --add item volume right \
  --subscribe volume volume_change system_woke \
  --set volume \
  update_freq=10 \
  script="$PLUGINS/volume.sh"

sketchybar --update

sketchybar --trigger aerospace_workspace_change \
  FOCUSED_WORKSPACE="$(aerospace list-workspaces --focused)"
