shell /opt/homebrew/bin/tmux new-session -A -s default

map cmd+t        send_text all \x01c
map cmd+1        send_text all \x011
map cmd+2        send_text all \x012
map cmd+3        send_text all \x013
map cmd+4        send_text all \x014
map cmd+5        send_text all \x015
map cmd+6        send_text all \x016
map cmd+7        send_text all \x017
map cmd+8        send_text all \x018
map cmd+9        send_text all \x019
map cmd+shift+w  send_text all \x01&
map cmd+n        send_text all \x01|
map cmd+shift+n  send_text all \x01-
map cmd+w        send_text all \x01x
map cmd+h        send_text all \x01h
map cmd+j        send_text all \x01j
map cmd+k        send_text all \x01k
map cmd+l        send_text all \x01l

font_family      JetBrainsMono NF
bold_font        JetBrainsMono NF Bold
italic_font      JetBrainsMono NF Italic
bold_italic_font JetBrainsMono NF Bold Italic
font_size        16.0
modify_font cell_height 110%

window_padding_width 12
scrollback_lines 10000
confirm_os_window_close 0

tab_bar_style hidden
hide_window_decorations titlebar-only

# Kanagawa Dragon
background            #181616
foreground            #c5c9c5
selection_background  #2D4F67
selection_foreground  #C8C093
cursor                #C8C093
cursor_text_color     #181616
url_color             #72A7BC

# Normal colors
color0  #0d0c0c
color1  #c4746e
color2  #8a9a7b
color3  #c4b28a
color4  #8ba4b0
color5  #a292a3
color6  #8ea4a2
color7  #C8C093

# Bright colors
color8  #a6a69c
color9  #E46876
color10 #87a987
color11 #E6C384
color12 #7FB4CA
color13 #938AA9
color14 #7AA89F
color15 #c5c9c5
